name: Docker Image CI arm7

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build_release:
    name: build_release
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      #      - name: release data
      #        run: |
      #              echo "::set-output rname=New release 123"
      #              echo "::set-output tname=noshit_1.2.3_release1"
      #        id: data_release
      - name: build docker
        run: docker build -t app-build-r-arm7 -f Dockerfile_r_arm7 .
      - name: build app
        run: docker run --rm -v "$PWD":/home/source app-build-r-arm7
      - name: release
        uses: actions/create-release@v1
        id: create_release
        with:
          draft: false
          prerelease: false
          release_name: New release 1233
          tag_name: noshit_1.2.3_release1_3
          body_path: README.md
        env:
          GITHUB_TOKEN: ${{ github.token }}
      - name: upload apk artifacts
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./app/build/outputs/apk/armeabi_v7a/release/app.apk
          asset_name: test-app-arm7.apk
          asset_content_type: application/gzip