name: Docker Image CI armeabi_v7a

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build_release:
    name: build_release
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: build docker
        run: docker build -t app-build-r-arm7 -f Dockerfile_r_arm7 .
      - name: build app
        run: docker run --rm -v "$PWD":/home/source app-build-r-arm7
      - name: release
        if: github.event.pull_request.merged
        uses: actions/create-release@v1
        id: create_release
        with:
          draft: false
          prerelease: false
          release_name: ${{ env.RNAME }}
          tag_name: ${{ env.TNAME }}${{ env.AARCH }}
        env:
          GITHUB_TOKEN: ${{ github.token }}
      - name: upload apk artifacts
        if: github.event.pull_request.merged
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./app/build/outputs/apk/${{ env.AARCH }}/release/app.apk
          asset_name: ${{ env.ANAME }}${{ env.AARCH }}.apk
          asset_content_type: application/gzip
    env:
      RNAME: New release 321
      TNAME: noshit_1.2.3_r1_
      ANAME: testApp
      AARCH: armeabi_v7a