name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build_release:
    name: build_release
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      #      - name: release data
      #        run: |
      #              echo "::set-output rname=New release 123"
      #              echo "::set-output tname=noshit_1.2.3_release1"
      #        id: data_release
      - name: build docker
        run: docker build -t app-build-r-arm8 -f Dockerfile_r_arm8 .
      - name: build app
        run: docker run --rm -v "$PWD":/home/source app-build-r-arm8
      - name: list files fuck
        run: |
          ls -la .
#          ls -la /home/source
#          ls -la /home/source/app/build
#          ls -la /home/source/app/build/outputs/apk/
#          ls -la /home/source/app/build/outputs/apk/arm64_v8a
#          ls -la /home/source/app/build/outputs/apk/arm64_v8a/release
#          ls -la /home/source/app/build/outputs/apk/arm64_v8a/release/app.apk
      - name: release
        uses: actions/create-release@v1
        id: create_release
        with:
          draft: false
          prerelease: false
          release_name: New release 123
          tag_name: noshit_1.2.3_release1_1
          body_path: README.md
        env:
          GITHUB_TOKEN: ${{ github.token }}
      - name: upload apk artifacts
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: /home/source/app/build/outputs/apk/arm64_v8a/release/app.apk
          asset_name: test-app-arm8.apk
          asset_content_type: application/gzip